spring.application.name=api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost

# Patient Service
spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/patients/**

# Appointment Service
spring.cloud.gateway.server.webflux.routes[1].id=appointment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/appointments/**

# Billing Service
spring.cloud.gateway.server.webflux.routes[2].id=billing-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BILLING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/billing/**
# CORS for React frontend
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,http://localhost:5174,http://localhost:5175
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true